builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["nodePackages.npm", "python3", "libglvnd", "glib"]

[phases.build]
cmds = ["npm install", "pip install -r requirements.txt", "npm run build", "chmod +x scripts/start.sh"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
healthcheckInterval = 30
numReplicas = 1
sleepApplication = false
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[env]
# Увеличиваем таймауты Node.js и ограничиваем память до разумных 4ГБ
NODE_OPTIONS = "--max-old-space-size=4096"